# Generated by Django 5.1.4 on 2025-01-19 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='course_content/')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('text', 'Text')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.content')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
    ]
